version: 2
jobs:
   build:
     docker:
       - image: waterswims/ubuntu-openmp-hdf5:0.0.1
     steps:
       - checkout
       - run: git submodule init
       - run: git submodule update
       - run: make
       - run: make clean
       - run: make test
       - run: LD_LIBRARY_PATH="/opt/hdf5/lib:${LD_LIBRARY_PATH}" ./test
